name: dev ci

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Packages Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/dev' }}
          tags: |
            ghcr.io/${{ github.repository }}:dev
            ghcr.io/${{ github.repository }}:run-${{ github.run_id }}-${{ github.run_attempt }}
            ghcr.io/${{ github.repository }}:dev-${{ github.run_id }}-${{ github.run_attempt }}
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}